project:
  type: website
website:
  title: "6235 - Data Literacy"
  repo-url: https://github.com/dwinkler1/dl
  site-url: https://dwinkler.org/dl
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: 00-admin.qmd
        text: Introduction to the course
format:
  html:
    theme: flatly
    css: styles.css
    toc: true

